### ISSUE TITLE
Bank Check

### ISSUE THREAD

**Issue by Delphi79** [Grimoric/RunUO.T2A#11]
Bank checks were in the last patch of T2A. Not sure if you are keeping them but if so here is a problem. 
Bankers do not recognize bank checks in bankbox and will tell you your gold balance is 0 no matter what the check value is.

**Comment by SakuraUO** [comment]
I don't recall Bank Checks ever being introduced in T2A. I thought they were introduced in Age of Shadows.

**Comment by Delphi79** [comment]
Nope Bank Checks were released before AOS. According to the patchnotes for 03/09/2000.
http://wiki.uosecondage.com/Ultima_Online:_The_Second_Age_Patch_Notes_for_03/09/2000 

OU R wasn't released till May of 2000. https://en.wikipedia.org/wiki/Ultima_Online So it must have been T2A.

AOS was released in Feb of 2003 so bankchecks were almost 3 years old by then.

**Comment by SakuraUO** [comment]
Oh, my bad then. I thought they didn't release Bank Checks until AOS. I apologize for my ignorance.

**Comment by Delphi79** [comment]
It's hard to get accurate times and date on this stuff. LOL No need to apologize, I get corrected all the time about this date and that etc. I'm learning what is what in T2A too. :D

**Comment by Grimoric** [comment]
Bank checks have been removed in r23
