### ISSUE TITLE
Deco File for magencia bank

### ISSUE THREAD

**Issue by Delphi79** [Grimoric/RunUO.T2A#15]
Can you add these items to the magencia.cfg file so that when you decorate the bank in magencia is fully generated?

#Bank Door
MetalDoor2 0x06CF (Facing=NorthCCW)
3735 2147 20

#Bank BookShelves
FullBookcase 0x0A97
3729 2144 20
3731 2144 20

#Bank Chest
FillableMetalGoldenChest 0x0E41
3730 2144 20
3732 2144 20

#Bank Wooden Chair
WoodenChair 0x0B57
3730 2146 20

#Bank Bulletin Board
BulletinBoard 0x1E5F
3728 2152 20

#Bank Benches 1
Static 0x0B93
3728 2155 20
3728 2150 20

#Bank Benches 2
Static 0x0B94
3728 2154 20
3728 2149 20

#Bank Metal Box
FillableMetalBox 0x09A8
3729 2147 26

**Comment by Grimoric** [comment]
Fixed!
