### ISSUE TITLE
T2A FeatureFlags and Music handling

### ISSUE THREAD

**Issue by LeonG-ZA** [Grimoric/RunUO.T2A#20]
Hi,
I would like to know what extra features would be enabled in the Ultima Online client if an 'LBR' flag is sent instead of 'T2A'?
I know the music handling is different, but is there anything else that would negatively impact a T2A shard?
When the T2A flag is sent then the client plays MIDIs from the 'Music' folder.
When the LBR flag is sent then the client plays MP3s from the 'Music\Digital' folder.
 
The reason why I'm asking is that the old T2A way of playing music isn't very compatible with newer clients such as 5.0.8.4 and 5.0.9.1. There is a slight delay that freezes the client when changing MIDIs.
I know that there is a 'music fix' client hack so that MP3s can be played back in the Music folder instead of the MIDIs so that the client doesn't hang, but there still is an issue where changing regions that the music packet is ignored(sometimes).

A few years back there was a discussion on the Second Age forums: http://forums.uosecondage.com/viewtopic.php?f=8&t=38503
http://forums.uosecondage.com/viewtopic.php?p=333658#p333658

**Comment by Grimoric** [comment]
All types of expansion checks on the server side has been removed so there will not be any new content activated (Like new monster graphics) by setting this flag. You will not find anything different on the client side either because all the features are locked by higher expansions. (Race and templates like ninja or paladin.)

**Comment by LeonG-ZA** [comment]
Thanks Grimoric, that was my thinking as well. Just wanted to make sure that I wasn't missing something :)
So it is actually safe to use the LBR flag for a T2A shard.
