### ISSUE TITLE
Xmlspawner possible?

### ISSUE THREAD

**Issue by DevOptimusPrime** [Grimoric/RunUO.T2A#21]
Downloaded the repo and got it working - thanks so much for this, my friends and I love the T2A era. 

I'd like to add some surprises for them - is using XmlSpawner a possibility?

**Comment by Grimoric** [comment]
Depends on what you like to do. It has to be rewritten sins this version is heavily modified. This T2A installation doesn't support AOS damages and item stats that Xmlpawner is using. There are no Quest NPCs in T2A so what would not be supported. 

I can look into it and make the standard spawning features work. It would be a RunUO.T2A version.

**Comment by Grimoric** [comment]
I have added a basic T2A version XmlSpawner2 v3.24 (updated 2/11/08 by ArteGordon) to the project. This needs to be tested but it should work. We will need a good T2A spawn map for this too.

**Comment by DevOptimusPrime** [comment]
Whoa! Thanks!

I was able to get some of the stuff I was experimenting with by just
editing the source, but I am eager to try this. Mostly this is for me and
my friends to play, but I wanted to add some surprises for them.
